# coding: utf-8

# flake8: noqa
"""
    TON Rocket Pay API

    This API based on @tonRocketBot (@ton_rocket_test_bot for testnest) Payment System. In order to use it, you need to get API key from bot. Open it and go to Rocket Pay > Create App > API token.<br><br>This page is fully interactive. Provide obtained API key to AUTHORIZE button on the right, and you can try all API methods by simply clicking buttons and filling forms here<br><br>API token must be specified in header of each request. Header name is <b>Rocket-Pay-Key</b>. Only exception is /version endpoint<br><br>If endpoint can send webhooks in response, it is provided on endpoint page on Callbacks bookmark. Now only /tg-invoices endpoint sends webhooks. You can turn them on in bot in app management page<br>In order to verify webhooks information integrity, we send you in headers parameter <b>rocket-pay-signature</b>, which is hex representation of HMAC-SHA-256 signature used to sign request body with a secret key that is SHA256 hash of your app token.<br><br>This specification fully complies with OpenAPI 3.0 standard, so if you want to see schemas of request bodies or responses, please click \"Schema\" inside endpoint. All mandatory fields marked with *, all types and limits also described inside schemas<br><br><h2>Change Log</h2><h3>version 1.3</h3>Added support for multi-invoices:<br>post /tg-invoices - added request parameter numPayments (default - 1), added response parameter totalActivations, activationsLeft<br>webhook /tg-invoices - added parameter payment (telegram user ID and number of items purchased for this payment)<br>get /tg-invoices - added response parameter totalActivations, activationsLeft<br>get /tg-invoices/{id} - added response parameter numPayments and payments (list, info about payments that were maid for this invoice)<br>  # noqa: E501

    OpenAPI spec version: 1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.all_of_cheque_disabled_languages import AllOfChequeDisabledLanguages
from swagger_client.models.all_of_coin_dto_fee_withdraw import AllOfCoinDtoFeeWithdraw
from swagger_client.models.all_of_pay_invoice_dto_payment import AllOfPayInvoiceDtoPayment
from swagger_client.models.all_of_short_cheque_dto_disabled_languages import AllOfShortChequeDtoDisabledLanguages
from swagger_client.models.all_of_subscription_interval import AllOfSubscriptionInterval
from swagger_client.models.all_of_subscription_tg_resource import AllOfSubscriptionTgResource
from swagger_client.models.api_bad_request_error import ApiBadRequestError
from swagger_client.models.api_error import ApiError
from swagger_client.models.app import App
from swagger_client.models.app_balance import AppBalance
from swagger_client.models.app_dto import AppDto
from swagger_client.models.available_coins import AvailableCoins
from swagger_client.models.available_coins_data import AvailableCoinsData
from swagger_client.models.check_subscription_dto import CheckSubscriptionDto
from swagger_client.models.cheque import Cheque
from swagger_client.models.coin_dto import CoinDto
from swagger_client.models.create_cheque_dto import CreateChequeDto
from swagger_client.models.create_invoice_dto import CreateInvoiceDto
from swagger_client.models.create_subscription_dto import CreateSubscriptionDto
from swagger_client.models.create_transfer_dto import CreateTransferDto
from swagger_client.models.create_withdrawal_dto import CreateWithdrawalDto
from swagger_client.models.delete_response_dto import DeleteResponseDto
from swagger_client.models.edit_subscription_interval_dto import EditSubscriptionIntervalDto
from swagger_client.models.full_invoice_dto import FullInvoiceDto
from swagger_client.models.full_invoice_response_dto import FullInvoiceResponseDto
from swagger_client.models.invoice import Invoice
from swagger_client.models.paginated_invoice_response import PaginatedInvoiceResponse
from swagger_client.models.paginated_short_cheque_dto_response import PaginatedShortChequeDtoResponse
from swagger_client.models.paginated_subscription_response import PaginatedSubscriptionResponse
from swagger_client.models.pagination_dto import PaginationDto
from swagger_client.models.pay_invoice_dto import PayInvoiceDto
from swagger_client.models.pay_invoice_stat_dto import PayInvoiceStatDto
from swagger_client.models.property_error import PropertyError
from swagger_client.models.rates import Rates
from swagger_client.models.response_dto import ResponseDto
from swagger_client.models.set import Set
from swagger_client.models.short_cheque_dto import ShortChequeDto
from swagger_client.models.simple_cheque_response import SimpleChequeResponse
from swagger_client.models.simple_full_invoice_dto_response import SimpleFullInvoiceDtoResponse
from swagger_client.models.simple_invoice_response import SimpleInvoiceResponse
from swagger_client.models.simple_short_cheque_dto_response import SimpleShortChequeDtoResponse
from swagger_client.models.simple_subscription_interval_response import SimpleSubscriptionIntervalResponse
from swagger_client.models.simple_subscription_response import SimpleSubscriptionResponse
from swagger_client.models.simple_transfer_dto_response import SimpleTransferDtoResponse
from swagger_client.models.simple_user_subscription_response import SimpleUserSubscriptionResponse
from swagger_client.models.simple_withdrawal_dto_response import SimpleWithdrawalDtoResponse
from swagger_client.models.subscription import Subscription
from swagger_client.models.subscription_interval import SubscriptionInterval
from swagger_client.models.subscription_interval_dto import SubscriptionIntervalDto
from swagger_client.models.subscription_resource import SubscriptionResource
from swagger_client.models.tg_resource import TgResource
from swagger_client.models.transfer_dto import TransferDto
from swagger_client.models.update_cheque_dto import UpdateChequeDto
from swagger_client.models.user_subscription import UserSubscription
from swagger_client.models.user_subscription_transaction import UserSubscriptionTransaction
from swagger_client.models.version import Version
from swagger_client.models.webhook_dto import WebhookDto
from swagger_client.models.withdraw_fee_dto import WithdrawFeeDto
from swagger_client.models.withdrawal_dto import WithdrawalDto
